<?php

/**
 * @file
 * Provides consolidated management of third-party Composer-compatible packages
 * required by contributed modules.
 */

/**
 * Implements hook_menu_link_defaults().
 */
function mymodule_menu_link_defaults() {
  $links = array();

  $links['system.admin.config.system.composer_manager'] = array(
    'link_title' => 'Composer Manager',
    'description' => 'View the status of packages managed by Composer and configure the location of the composer.json file and verdor directory.',
    'parent' => 'system.admin.config.system',
    'route_name' => 'composer_manager.packages_page',
  );

  return $links;
}

/**
 * Implements hook_modules_installed().
 *
 * @see composer_manager_write_if_changed()
 */
function composer_manager_modules_installed($modules) {
  composer_manager_write_if_changed($modules);
}

/**
 * Implements hook_modules_uninstalled().
 *
 * @see composer_manager_write_if_changed()
 */
function composer_manager_modules_uninstalled($modules) {
  composer_manager_write_if_changed($modules);
}

/**
 * Writes the composer.json file if one of the enabled / disabled modules
 * has a composer.json file.
 *
 * This is a primitive check to ensure that the composer.json file is built only
 * when it has changes. This check always passes when run via the command line,
 * as it is assumed that Drush is being used to enable or disable the the
 * modules.
 *
 * @param array $modules
 *   The enabled / disabled modules being scanned for a composer.json file.
 */
function composer_manager_write_if_changed(array $modules) {
  /* @var $packages Drupal\composer_manager\ComposerPackagesInterface */
  $packages = Drupal::service('composer_manager.packages');
  $manager = $packages->getManager();

  if ($manager->autobuildComposerJsonFile() && $packages->haveChanges($modules)) {
    if ($packages->writeComposerJsonFile() !== FALSE) {

      // Displays a message to admins that a file was written.
      if (Drupal::currentUser()->hasPermission('administer site configuration')) {

        $filepath = drupal_realpath($manager->getComposerJsonFile()->getFilepath());
        drupal_set_message(t('A composer.json file was written to @filepath.', array('@filepath' => $filepath)));

        $command = $manager->getComposerLockFile()->exists() ? 'update' : 'install';
        $args = array('!command' => $command, '@url' => url('http://drupal.org/project/composer_manager', array('absolute' => TRUE)));

        if ('install' == $command) {
          $message = t('Composer\'s <code>!command</code> command must be run to generate the autoloader and install the required packages.<br/>Refer to the instructions on the <a href="@url" target="_blank">Composer Manager project page</a> for installing packages.', $args);
        }
        else {
          $message = t('Composer\'s <code>!command</code> command must be run to install the required packages.<br/>Refer to the instructions on the <a href="@url" target="_blank">Composer Manager project page</a> for updating packages.', $args);
        }
        drupal_set_message($message, 'warning');
      }
    }
  }
}
